project_id = "ktkfuquqxbrmuqrmbmdj"

[functions.tally-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.unblock-user]
verify_jwt = false

