update public.boiler_fault_codes c set possible_causes=ARRAY['Boiler/CH system not full, or isolation, system filter or radiator valves closed','Flow/return differential across boiler above 30°C: check pump rotates freely; replace pump if differential does not fall below 20°C','If differential not above 30°C: check flow and return thermistors (sections 3.14 & 3.29)']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p55): 4.2 Overheat Lockout: fill/vent and open valves; if flow/return differential >30°C check pump rotates freely and replace pump if differential does not fall below 20°C; otherwise check thermistors (Flow/Return/DHW thermistor resistance: 25°C 9.7–10.3 kΩ; 60°C 2.4–2.6 kΩ; 85°C 1.0–1.1 kΩ).' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Overheat' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Gas pressure at boiler inlet not above 18 mbar','No approx. 24 V DC at gas valve (wiring gas valve–PCB; else replace PCB)','Gas valve resistance across outside pins not 4 kΩ (±2) – replace gas valve','Electrode or harness: continuity, condition, position (section 3.9)','Spark generator or harness (section 3.15)','Blocked condensate trap/drain pipe']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p56): 4.3 Ignition Lockout flowchart, p56. If all checks pass, manual says replace gas valve.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Ignition Lockout' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Internal boiler wiring routing/integrity','Deteriorated electrode – replace']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p56): 4.4 Flame On Before Gas Valve On, p56: restart boiler; if not OK check internal wiring then electrode condition; replace electrode.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Flame On Before Gas On' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['System not filled / valves closed (gauge should read 1 to 1.5 bar)','Loose connections on water pressure switch','Faulty water pressure switch – replace']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p56): 4.5 Low Water Pressure flowchart, p56.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Low Water Pressure' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Gas pressure at boiler inlet not above 18 mbar','No 24 V DC at gas valve while flame on (wiring gas valve–PCB; else replace PCB)','Blocked condensate pipe or flue','Electrode or harness: continuity, condition, position (section 3.9)','Spark generator or harness (section 3.15)','Blocked condensate trap/drain pipe']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p57): 4.6 Flame Loss flowchart, p57. If all checks pass, manual says replace gas valve.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Flame Loss' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Fan–PCB wiring loose, deteriorated or no continuity','No 230 V AC at blue/brown of fan 3-way connector – replace PCB','230 V AC present – replace fan']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p57): 4.7 Fan Fault flowchart, p57.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Fan Fault' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Wiring loose at flow thermistor (heat exchanger, upper LHS)','Thermistor resistance out of range – fit new thermistor','Wiring loose at 6-way low-voltage connector, front LHS of PCB','Otherwise replace PCB']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p58): 4.8 Flow Thermistor Fault, p58. Flow/Return/DHW thermistor resistance: 25°C 9.7–10.3 kΩ; 60°C 2.4–2.6 kΩ; 85°C 1.0–1.1 kΩ' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Flow Thermistor Fault' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Thermistor (pump housing) resistance out of range – fit new thermistor','No continuity PCB–thermistor – check/replace wiring','Otherwise replace PCB']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p58): 4.9 Return Thermistor Fault, p58. Flow/Return/DHW thermistor resistance: 25°C 9.7–10.3 kΩ; 60°C 2.4–2.6 kΩ; 85°C 1.0–1.1 kΩ' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Return Thermistor Fault' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Wiring loose at boiler or outside sensor','Sensor resistance out of range (0°C 31.0–35.0 kΩ; 15°C 15.0–16.5 kΩ; 30°C 7.7–8.5 kΩ) – fit new sensor','Wiring loose between terminal block and PCB','Otherwise replace PCB']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p59): 4.10 Outside Sensor Fault, p59.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Outside Sensor Fault' and c.status='draft';
update public.boiler_fault_codes c set possible_causes=ARRAY['Thermistor resistance out of range (25°C 9.7–10.3 kΩ; 60°C 2.4–2.6 kΩ) – fit new thermistor','No continuity PCB–thermistor – check/replace wiring','Otherwise replace PCB']::text[], technical_details=c.technical_details || '
ENGINEER CHECKS (Installation & Servicing UIN 237662 A01, 10/2023, p61): 4.14 DHW Thermistor Fault, p61.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='DHW Thermistor Fault' and c.status='draft';
update public.boiler_fault_codes c set technical_details=c.technical_details || '
ENGINEER CHECKS: none documented for this message in Installation & Servicing UIN 237662 A01 section 4 (pp55-61).' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code in ('Room Thermostat Fault','Spare PCB Not Set','No Water Flow','Too Many Restarts','PCB Fault','Pump Rotor Blocked','Low Mains Voltage','Pump Dry Run','Pump Fault','Blocked Flue/Condensate','Gas Valve Fault') and c.status='draft';
update public.boiler_fault_codes c set explanation='The boiler has detected a gas valve fault. Restart available. If it persists, contact a registered gas installer.', technical_details=c.technical_details || '
SOURCE WORDING (User Guide p9, verbatim): "Gas Valve Fault – Contact electricity provider". Not repeated as advice – appears to be a printing error. REVIEW: wording discrepancy.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Gas Valve Fault' and c.status='draft';
update public.boiler_fault_codes c set technical_details=c.technical_details || '
REVIEW: wording discrepancy – User Guide "Overheat" vs I&S "Overheat Lockout".' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Overheat' and c.status='draft';
update public.boiler_fault_codes c set technical_details=c.technical_details || '
REVIEW: wording discrepancy – User Guide "Flame On Before Gas On" vs I&S "Flame On Before Gas Valve On".' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='Logic+ Combi2 C24 C30 C35' and c.code='Flame On Before Gas On' and c.status='draft';
insert into public.boiler_fault_models (brand,model_family,model_name,notes,status) select 'Baxi','400 Combi 2.1','400 Combi 2.1','Draft placeholder - NO codes copied. The Baxi Combi 2/2.1 combined manual (7875578-02) lists this model, but its error-code table (pp50-53) is not split by model; copy codes only after exact applicability is confirmed with Baxi. Output sizes not yet recorded.','draft' where not exists (select 1 from public.boiler_fault_models where brand='Baxi' and model_name='400 Combi 2.1');
insert into public.boiler_fault_models (brand,model_family,model_name,notes,status) select 'Baxi','800 Combi 2','800 Combi 2','Draft placeholder - NO codes copied. The Baxi Combi 2/2.1 combined manual (7875578-02) lists this model, but its error-code table (pp50-53) is not split by model; copy codes only after exact applicability is confirmed with Baxi. Separate from the existing Baxi 800 Combi draft model. Output sizes not yet recorded.','draft' where not exists (select 1 from public.boiler_fault_models where brand='Baxi' and model_name='800 Combi 2');
insert into public.boiler_fault_models (brand,model_family,model_name,notes,status) select 'Baxi','Assure 500 Combi 2','Assure 500 Combi 2','Draft placeholder - NO codes copied. The Baxi Combi 2/2.1 combined manual (7875578-02) lists this model, but its error-code table (pp50-53) is not split by model; copy codes only after exact applicability is confirmed with Baxi. Output sizes not yet recorded.','draft' where not exists (select 1 from public.boiler_fault_models where brand='Baxi' and model_name='Assure 500 Combi 2');
update public.boiler_fault_models set notes=notes || ' REVIEW NOTE F1: request a photograph of the original F1 boiler''s manufacturer data plate and its error display before any F1 entry is considered.' where brand='Baxi' and model_name='600 Combi 2 (24 - 30 - 36)' and status='draft' and notes not like '%REVIEW NOTE F1%';
update public.boiler_fault_codes c set technical_details=c.technical_details || '
REVIEW: awaiting Baxi confirmation - status unresolved.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='600 Combi 2 (24 - 30 - 36)' and c.code in ('E.04.254','H.03.54') and c.status='draft';
update public.boiler_fault_codes c set technical_details=c.technical_details || '
Status classification subject to technical sign-off.' from public.boiler_fault_models m where m.id=c.model_id and m.model_name='600 Combi 2 (24 - 30 - 36)' and c.code='H.02.00' and c.status='draft';