
-- Add missing columns to settings table
ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS owner_name text,
  ADD COLUMN IF NOT EXISTS business_email text,
  ADD COLUMN IF NOT EXISTS business_phone text,
  ADD COLUMN IF NOT EXISTS website text,
  ADD COLUMN IF NOT EXISTS vat_number text,
  ADD COLUMN IF NOT EXISTS business_address text,
  ADD COLUMN IF NOT EXISTS invoice_prefix text DEFAULT 'K',
  ADD COLUMN IF NOT EXISTS next_invoice_number integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS payment_terms text DEFAULT '30_days',
  ADD COLUMN IF NOT EXISTS default_repair_price numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS default_emergency_price numeric(10,2) DEFAULT 150,
  ADD COLUMN IF NOT EXISTS google_review_url text,
  ADD COLUMN IF NOT EXISTS template_booking_confirmation text,
  ADD COLUMN IF NOT EXISTS template_renewal_reminder text,
  ADD COLUMN IF NOT EXISTS template_review_request text,
  ADD COLUMN IF NOT EXISTS template_quote_sent text,
  ADD COLUMN IF NOT EXISTS template_payment_link text,
  ADD COLUMN IF NOT EXISTS renewal_reminder_days_1 integer DEFAULT 30,
  ADD COLUMN IF NOT EXISTS renewal_reminder_days_2 integer DEFAULT 7,
  ADD COLUMN IF NOT EXISTS renewal_reminders_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS review_request_hours integer DEFAULT 2,
  ADD COLUMN IF NOT EXISTS review_requests_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS payment_reminder_days_1 integer DEFAULT 7,
  ADD COLUMN IF NOT EXISTS payment_reminder_days_2 integer DEFAULT 14,
  ADD COLUMN IF NOT EXISTS payment_reminders_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS opening_hours jsonb DEFAULT '[{"day":"Mon","enabled":true,"start":"08:00","end":"17:00"},{"day":"Tue","enabled":true,"start":"08:00","end":"17:00"},{"day":"Wed","enabled":true,"start":"08:00","end":"17:00"},{"day":"Thu","enabled":true,"start":"08:00","end":"17:00"},{"day":"Fri","enabled":true,"start":"08:00","end":"17:00"},{"day":"Sat","enabled":true,"start":"09:00","end":"13:00"},{"day":"Sun","enabled":false,"start":"09:00","end":"13:00"}]'::jsonb,
  ADD COLUMN IF NOT EXISTS service_areas jsonb DEFAULT '["D15","D6","K67"]'::jsonb,
  ADD COLUMN IF NOT EXISTS job_time_blocks jsonb DEFAULT '[{"label":"Morning","start":"09:00","end":"11:00","max_jobs":2},{"label":"Midday","start":"11:00","end":"14:00","max_jobs":2},{"label":"Afternoon","start":"14:00","end":"17:00","max_jobs":2}]'::jsonb;
